spring:
  application:
    name: archive

  datasource:
    url: jdbc:mysql://localhost:3306/archive_db?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8_general_ci&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000 # 5 minutes
      pool-name: archive-pool
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 30000 # retry DB connecting attempt after 30 seconds
  sql:
    init:
      mode: always

  jpa:
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
#        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    database: mysql
    open-in-view: false

#logging:
#  level:
#    org.springdoc: debug
#    com.zaxxer.hikari: debug
#    org.hibernate.sql: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  address: ${pc.address}
  port: ${pc.port}

pc:
  address: 0.0.0.0
  port: 8083

springdoc:
  swagger-ui:
    enabled: true